name: 📦 Build & Deploy Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read    # for checkout
  pages: write      # to publish to GitHub Pages
  id-token: write   # required by deploy-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) checkout your code
      - uses: actions/checkout@v3

      # 2) assemble the static site into "site/"
      - name: Prepare static site
        run: |
          rm -rf site
          mkdir site
          cp templates/index.html site/index.html
          cp -r static site/static
          # inject the Mapbox key from your secret
          sed -i "s/{{ mapbox_key }}/$MAPBOX_KEY/g" site/index.html

      # 3) upload to the Pages artifact (NOT upload-artifact!)
      - uses: actions/upload-pages-artifact@v1
        with:
          path: site

      # 4) deploy to gh-pages
      - uses: actions/deploy-pages@v1
