name: 📦 Build & Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write      # to checkout your code
  pages: write        # to create/update gh-pages branch
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out main
      - uses: actions/checkout@v3

      # 2) Assemble a 'site/' directory
      - name: Prepare static site
        env:
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
        run: |
          rm -rf site
          mkdir site
          # Copy your HTML + static assets
          cp templates/index.html site/index.html
          cp -r static site/static
          # Inject the real Mapbox token
          sed -i "s/{{ mapbox_key }}/$MAPBOX_API_KEY/g" site/index.html

      # 3) Deploy via pushing to gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
